### ISSUE TITLE
Clicking on specific link crashes app

### ISSUE THREAD

**Issue by Zyranix** [jbb01/QED#34]
Clicking inside the app on the link https://qedgallery.qed-verein.de/image_view.php?imageid=30821​ (i.e. in a chat) crashes the app. Other gallery-links work as intended (showing the resource in the in-app viewer).

My specs: Galaxy S21 FE / Android 13
App version 3.0.0-rc1

**Comment by jbb01** [comment]
The problem doesn't seem to be limited to (some) gallery links as the app seems to crash for all database deep links (e.g. https://qeddb.qed-verein.de/events/89), although it seems the root cause is different. The database link issue seems to be caused by changes made in 2840b1e.

**Comment by vlg01** [comment]
the first link is faulty, it adds %u200B to the url

**Comment by Zyranix** [comment]
@vlg01 Ah you're right, I had a look into the chat again for context, and they added a zero-width whitespace at the end. There is also the same link without this, and it works just fine. Probably the link parser just doesn't skip all special symbols?

![grafik](https://github.com/jbb01/QED/assets/45319412/e8dae090-b15a-469b-8ea7-545db88e6f5a)
